FROM yukaitung/lgdxrobot2.support:arm64

# LGDXRobot2 ROS2
WORKDIR /config/lgdx_ws/src
COPY . .

WORKDIR /config/lgdx_ws
RUN . /opt/ros/$ROS_DISTRO/setup.sh && \
      . /config/webots_ws/install/setup.sh && \
      colcon build --symlink-install

COPY ./ros_entrypoint.sh /
RUN chmod +x /ros_entrypoint.sh

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]