FROM yukaitung/lgdxrobot2.support:amd64-desktop

RUN apt update && \
      apt upgrade -y && \  
      rm -rf /var/lib/apt/lists/*

# LGDXRobot2 ROS2
WORKDIR /home/user/lgdx_ws/src
COPY . .

WORKDIR /home/user/lgdx_ws
RUN . /opt/ros/$ROS_DISTRO/setup.sh && \
      . /home/user/webots_ws/install/setup.sh && \
      colcon build

COPY ./ros_entrypoint.sh /
RUN chmod +x /ros_entrypoint.sh

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]

EXPOSE 3000
EXPOSE 3001
VOLUME /config