/depthimage_to_laserscan:
  ros__parameters:
    output_frame: camera_depth_frame
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    range_max: 10.0
    range_min: 0.45
    scan_height: 1
    scan_time: 0.033
    use_sim_time: false