<ROS_NAMESPACE>/explore_node:
  ros__parameters:
    robot_base_frame: base_link
    return_to_init: False
    costmap_topic: map
    costmap_updates_topic: map_updates
    visualize: true
    planner_frequency: 0.5
    progress_timeout: 60.0
    potential_scale: 5.0
    orientation_scale: 0.0
    gain_scale: 0.5
    transform_tolerance: 0.3
    min_frontier_size: 0.75