### ekf config file ###
<ROS_NAMESPACE>/ekf_filter_node:
    ros__parameters:
        frequency: 50.0
        two_d_mode: true
        publish_tf: true
        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom

        odom0: <ROS_NAMESPACE>/agent/odom
        odom0_config: [false, false, false,
                       false, false, false,
                       true,  true,  false,
                       false, false, true,
                       true,  true,  false]

        imu0: <ROS_NAMESPACE>/imu/data
        imu0_config:   [false, false,  false,
                        false, false,  true,
                        false, false,  false,
                        false, false,  true,
                        false, false,  false]