lgdxrobot2_mcu:
  ros__parameters:
    base_link_frame: base_link
    control_mode: cmd_vel
    publish_odom: true
    publish_tf: false
    use_external_imu: true
    reset_transform: true
    serial_port: ''