<ROS_NAMESPACE>/lgdxrobot2_agent_node:
  ros__parameters:
    mcu_enable: true
    mcu_control_mode: "cmd_vel"
    mcu_reset_transform: true
    mcu_publish_odom: true
    mcu_publish_tf: false
    mcu_base_link_name: "base_link"
    mcu_publish_joint_state: true
