/camera/camera:
  ros__parameters:
    align_depth:
      enable: true
    accel_qos: SYSTEM_DEFAULT
    depth_module:
      profile: 1280x720x30
    pointcloud:
      enable: true
      pointcloud_qos: SENSOR_DATA
    enable_accel: true
    enable_color: true
    enable_depth: true
    enable_gyro: true
    enable_sync: true
    enable_rgbd: true
    gyro_qos: SYSTEM_DEFAULT
    unite_imu_method: 2