### ekf config file ###
<ROS_NAMESPACE>/ekf_filter_node:
    ros__parameters:
        frequency: 30.0
        two_d_mode: true
        publish_acceleration: true
        publish_tf: true
        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom

        odom0: /agent/odom
        odom0_config: [true,  true,  false,
                       false, false, true,
                       true,  true,  false,
                       false, false, false,
                       false, false, false]

        imu0: /imu/data
        imu0_config:   [false, false,  false,
                        false, false,  false,
                        true,  true,   false,
                        false, false,  true,
                        false, false,  false]