FROM yukaitung/lgdxrobot2:dev-arm64 AS lgdxrobot2

FROM yukaitung/lgdxrobot2.supportdesktop:arm64

# LGDXRobot2 ROS2
COPY --from=lgdxrobot2 /config/lgdx_ws /config/lgdx_ws

COPY ./ros_entrypoint.sh /
RUN chmod +x /ros_entrypoint.sh

# ChassisTuner
WORKDIR /config
RUN wget https://gitlab.com/yukaitung/lgdxrobot2-chassistuner/-/package_files/247453314/download
RUN mv ChassisTuner-arm64 ChassisTuner

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["/init"]

EXPOSE 3000
EXPOSE 3001
VOLUME /config