FROM yukaitung/lgdxrobot2:dev-amd64 AS lgdxrobot2

FROM yukaitung/lgdxrobot2.supportdesktop:amd64

# LGDXRobot2 ROS2
COPY --from=lgdxrobot2 /config/lgdx_ws /config/lgdx_ws

COPY ./ros_entrypoint.sh /
RUN chmod +x /ros_entrypoint.sh

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["/init"]

EXPOSE 3000
EXPOSE 3001
VOLUME /config