FROM yukaitung/lgdxrobot2.desktop:dev-amd64-lite

# Install Webots
WORKDIR /etc/apt/keyrings
RUN sudo wget -q https://cyberbotics.com/Cyberbotics.asc
RUN echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/Cyberbotics.asc] https://cyberbotics.com/debian binary-amd64/" | sudo tee /etc/apt/sources.list.d/Cyberbotics.list

RUN apt update && \
      apt install --no-install-recommends -y webots && \
      rm -rf /var/lib/apt/lists/*